# db-mysql/tasks/main.yml
---
- name: Install MySQL packages
  ansible.builtin.yum:
    name: mysql-server
    state: present
  become: yes

- name: Start and enable MySQL service
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: true
  become: yes

- name: Set MySQL root password
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ db_password }}"
    check_implicit_admin: yes
  become: yes
  when: db_password is defined
